---
# all role tasks
#

# Add LXC daily build repo
- name: Add LXC and LXD Daily Build Repos
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'ppa:ubuntu-lxc/lxd-git-master'
    - 'ppa:ubuntu-lxc/daily'

# Update debian cache
- name: Update apt-cache
  apt: update_cache=yes cache_valid_time=86400

# Install default packages we like working with
- name: Install general support packages
  apt: name={{ item }} state=latest
  with_items:
    - vim
    - htop
    - dstat
    - mlocate
    - python-dev
    - libpython-dev
    - python-pip

# lxc build-essential protobuf-c-compiler asciidoc
# Install packages for container migration
- name: Install LXD packages and such for container migration demo
  apt: name={{ item }} state=latest
  with_items:
    - lxd
    - lxd-client
    - lxc-dev

# pip install lxc-python2
- name: pip install lxc-python2
  pip: name=lxc-python2 state=present

# Copy phidgets library zip.  If updated, kick off unpack and install.
# - name: create bridged network adapter
#   copy: src=doombr.cfg dest=/etc/network/interfaces.d/doombr.cfg
#   notify: reload network
